LedgerHQ/ledger-wallet-daemon

.dockerignore, Dockerfile
The file will:
- Pull a docker container based on ubuntu (for libstdcxx.so)
- Install oracle JDK 8
- Install SBT
- Build the sources
=> Create a base configuration file for Docker

daemon/src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala
Support for new BTC like coins
=> add matching coin -> ticker in ApiClient

.dockerignore, Dockerfile, daemon/src/main/resources/application.conf.sample, docker/build.sh, docker/install_run_deps.sh, docker/run.sh
Using openjdk 8 (u181) should be change/update via the Dockerfile
Using embeded libledger-core jar
=> INFRA:332 Dockerize Wallet Daemon

daemon/src/main/scala/co/ledger/wallet/daemon/models/Account.scala, daemon/src/main/scala/co/ledger/wallet/daemon/models/Wallet.scala, ledger-core-binding/src/main/java/djinni/NativeLibLoader.java
- Remove cache for last block height to prevent bad confirmation number
- Sort operations by date (descending)
=> Various fixes

daemon/src/main/scala/co/ledger/wallet/daemon/database/DefaultDaemonCache.scala, daemon/src/main/scala/co/ledger/wallet/daemon/models/Pool.scala, daemon/src/main/scala/co/ledger/wallet/daemon/models/Wallet.scala, daemon/src/test/scala/co/ledger/wallet/daemon/models/PoolTest.scala
Existing tests passed, add more tests for the change.
=> Remove caching from Pool

build.sbt, daemon/src/main/resources/logback.xml, daemon/src/main/scala/co/ledger/wallet/daemon/Server.scala, daemon/src/main/scala/co/ledger/wallet/daemon/filters/CorrelationIdFilter.scala
So we can follow CID in all services, i.e. gate, hsm and daemon
=> log correlation ID send from gate

.circleci/config.yml
This is a preliminary work to implement automatic rebuild of the Docker
image through CircleCI.
=> INFRA-344: Refresh Docker image through CircleCI

daemon/src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, daemon/src/main/scala/co/ledger/wallet/daemon/libledger_core/filesystem/ScalaPathResolver.scala
add config "core_data_path" with default "./core_data"
=> LV-605: [DAEMON] move sqlite db located in folder of jar's libcore.

src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala
Relates to https://github.com/twitter/finagle/issues/523
=> Use most recent proxy mechanism from Finatra

src/main/resources/application.conf.sample
Applying a hotfix on master to allow deploying the new ETH explorers on prod.
=> Retrieve explorer and ws endpoints from env var

src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala
This is to debug the gas limit issue with ERC20 tokens.
=> Add log to getGasLimit function

build.sbt, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
If our explorer v3 does not respond after x ms, we are using infura API.
=> Infura fallback

build-jar.sh, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/controllers/TransactionsController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/responses/ResponseSerializer.scala, src/main/scala/co/ledger/wallet/daemon/exceptions/Exceptions.scala, src/main/scala/co/ledger/wallet/daemon/mappers/DaemonExceptionMapper.scala, src/main/scala/co/ledger/wallet/daemon/mappers/LibCoreExceptionMapper.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/models/Pool.scala, src/main/scala/co/ledger/wallet/daemon/models/Wallet.scala, src/main/scala/co/ledger/wallet/daemon/models/coins/Ripple.scala
Some small fixes + integration related to the following libcore PRs:
- https://github.com/LedgerHQ/lib-ledger-core/pull/287
- https://github.com/LedgerHQ/lib-ledger-core/pull/290
- https://github.com/LedgerHQ/lib-ledger-core/pull/293
- https://github.com/LedgerHQ/lib-ledger-core/pull/294
- https://github.com/LedgerHQ/lib-ledger-core/pull/295
- https://github.com/LedgerHQ/lib-ledger-core/pull/299
- https://github.com/LedgerHQ/lib-ledger-core/pull/300
=> Additional fixes for XRP

src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/libledger_core/async/LedgerCoreExecutionContext.scala, src/main/scala/co/ledger/wallet/daemon/libledger_core/async/ScalaThreadDispatcher.scala, src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
Share one Pool for CPU instensive operations on libcore side
=> Back 363 thread control

src/main/resources/logback.xml, src/main/scala/co/ledger/wallet/daemon/Server.scala, src/main/scala/co/ledger/wallet/daemon/controllers/AccountsController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/CurrenciesController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/WalletPoolsController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/WalletsController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/responses/ResponseSerializer.scala, src/main/scala/co/ledger/wallet/daemon/mappers/DaemonExceptionMapper.scala, src/main/scala/co/ledger/wallet/daemon/mappers/LibCoreExceptionMapper.scala
Enhance Logging when error occur 
Enable AccessLogger logs
=> [Back-386] error and access logging

src/main/scala/co/ledger/wallet/daemon/clients/HttpCoreClientPool.scala, src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClientPool.scala, src/main/scala/co/ledger/wallet/daemon/controllers/WalletPoolsController.scala, src/main/scala/co/ledger/wallet/daemon/utils/Utils.scala
Backport fixes made while QAing 2.6.0
=> 2.6.0 stable

src/it/scala/co/ledger/wallet/daemon/api/AccountsApiTest.scala, src/main/scala/co/ledger/wallet/daemon/controllers/AccountsController.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
This is related to : https://ledgerhq.atlassian.net/browse/BACK-528
=> Add UTXO count to response when querying UTXOs on Account controller

src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
we need this info to build utxo view
=> return tx hash and output index in utxo view

src/it/scala/co/ledger/wallet/daemon/api/TransactionsApiTest.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, tooling/database/postgres/dbs.sh
Give the ability to exclude utxo with index
Test exclusion feature
=> Back 597 utxo exclusion api refresh

src/it/scala/co/ledger/wallet/daemon/services/FallbackServiceTest.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala, src/main/scala/co/ledger/wallet/daemon/services/FallbackService.scala
Add Fallbackservice
Test ERC and ETH balances
Reproduce and handle issue from MO-1310
0x answer from our provider is considered as Zero
=> BACK-794 : isolate, test fallback service and manage 0x empty responses

src/it/scala/co/ledger/wallet/daemon/models/WalletTest.scala, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/database/DefaultDaemonCache.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/models/Pool.scala, src/main/scala/co/ledger/wallet/daemon/models/Wallet.scala
Broken WebSocket option from Wallet Daemon
=> BACK-787 : remove websocket realtime libcore functionality

src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala, src/main/scala/co/ledger/wallet/daemon/services/Publisher.scala, src/main/scala/co/ledger/wallet/daemon/services/RabbitMQPublisher.scala
Avoid switching context of libcore objects for NRT only
=> Back-1020 : fix nrt jni ctx

src/it/scala/co/ledger/wallet/daemon/database/WalletPoolDAOTest.scala, src/main/scala/co/ledger/wallet/daemon/database/core/operations/StellarDao.scala, src/main/scala/co/ledger/wallet/daemon/models/Wallet.scala
Add an implementation for StellarDao to query stellar operations from the database.
=> Add StellarDao implementation and tests

Dockerfile, build.sbt, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/Server.scala, src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClientPool.scala, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala
todo: 
- use env var for datadog-agent dd trace host and port
- not launch ddtrace client if no dd agent var is declare
=> enable dd apm

src/main/scala/co/ledger/wallet/daemon/utils/NativeLibLoader.java
This PR gets rid of the pesky FileSystemAlreadyExistsException at startup
=> Fix FileSystemAlreadyExistsException

src/main/scala/co/ledger/wallet/daemon/models/Operations.scala
In staging we sometimes met the following exception:
```
021-02-17 10:43:34,282 walletdaemon-IO-2192 TraceId=d1346463bad304e4 CorrelationId= [ERROR] ThrowableExceptionMapper : Unhandled Exception
java.lang.RuntimeException: trying to use a destroyed object (Operation)
at co.ledger.core.Operation$CppProxy.getBlockHeight(Operation.java:316)
at co.ledger.wallet.daemon.models.Operations$.$anonfun$confirmations$1(Operations.scala:21)
at scala.runtime.java8.JFunction1$mcJJ$sp.apply(JFunction1$mcJJ$sp.java:23)
at scala.util.Success.$anonfun$map$1(Try.scala:255)
at scala.util.Success.map(Try.scala:213)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33) …
```
=> Fix usage of operation after being destroyed

src/main/scala/co/ledger/wallet/daemon/services/AccountOperationsPublisher.scala
We were missing the implementation of batched ERC20 operations update
=> Add batch support for ERC20 tokens
