.circleci/config.yml, .circleci/goss.yaml, .circleci/goss_wait.yaml
This is the same PR as this one on [notifcation-server](https://github.com/LedgerHQ/notification-server/pull/3).
The goss validation is run twice because the sed stub that extracts the JUnit XML result eats all other ouput, including errors not pertaining to the validation check itself. So the first run is to make sure goss passes well and then the second run is here to only extract the JUnit result and is guaranteed to be successful.
This  may not be a beautiful solution, but the only other way would be to use `tee` to write the output to a file as well and then extracting the JUnit result file. I thought that it would be more complicated to maintain.
=> INFRA-369 : Test the health endpoint of the created image

.circleci/config.yml
For dev & staging environment, infra development, continuous
deployment, we may need an image to deploy.
=> Publish a docker image on latest develop & release_candidate

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
In the case of erc20 tokens, the gas limit should be estimated using the contract address as the recipient.
For vanilla eth, we keep the actual recipient to do the estimation.
=> Use contract address if available to compute gas limit

README.md
typo and links and also cmake is missing on osx
PATH="/Applications/CMake.app/Contents/bin":"$PATH"
or you can use this: 
sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install
=> typo and links

src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala
New lib core version which stores eip55 formatted contract addresses
+ hotfix when calling explorer to get gas limit
=> Update lib core to produce eip55 addresses and handle lowercase bug

.circleci/config.yml, src/main/scala/co/ledger/wallet/daemon/controllers/TransactionsController.scala, src/main/scala/co/ledger/wallet/daemon/models/Operations.scala, src/main/scala/co/ledger/wallet/daemon/models/coins/Bitcoin.scala, src/main/scala/co/ledger/wallet/daemon/models/coins/Ethereum.scala
Update all the interfaces to send/expect every monetary amount as a string and ensure we don't lose precision in the communication.
=> Expect string amounts and parse them when creating transactions

src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala
This hotfix was done on master during the latest release and never applied on dev.
https://github.com/LedgerHQ/ledger-wallet-daemon/pull/95
It extends the validity time of the auth tokens sent by the gate. A more in-depth work is required to remove this auth as much as possible.
=> Increase the time of token validity

src/main/scala/co/ledger/wallet/daemon/exceptions/Exceptions.scala, src/main/scala/co/ledger/wallet/daemon/mappers/DaemonExceptionMapper.scala, src/main/scala/co/ledger/wallet/daemon/models/Currency.scala, src/main/scala/co/ledger/wallet/daemon/services/CurrenciesService.scala
When building a `currencyView` for a currency not supported by the Daemon, we raise an exception. This prevents listing all currencies when one of them has not been yet implemented on the Daemon and by extension on the gate.
By skipping the currencies generating exceptions, we make ourselves more resilient to libcore changes.
=> Skip unsupported currencies such as XRP

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
Unlike base currencies, it is possible to empty a token account by sending out all the tokens inside it since the fees are taken from the parent account.
=> Allow sending out the whole content of an erc20 account

build-jar.sh
Pointing to a new version of the lib-core https://github.com/LedgerHQ/lib-ledger-core/commit/4ff95fde74511d2c0c882e7bc72406c84d7e8383
=> Updated build-jar and lib-core jar to 4ff95fde

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
This is a hot fix related to https://ledgerhq.atlassian.net/browse/LV-1678
**Note:**
This UTXO picking strategy was not tested yet in production, we have tests covering it and I ran several tests with xpub with a lot of UTXOS and it seems to work just fine.
=> Change btc tx creation strategy to OPTIMIZE_SIZE

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
When debugging, core team need the sign tx
I could not find this info logged anywhere so I am not sure how did we debugged wrong tx in production.
=> add log of eth tx

build-jar.sh
Fixes libcore bug related to incorrect timestamps after account reconciliation.
=> Bump libcore version to 3.1.0-rc-da6037

src/main/scala/co/ledger/wallet/daemon/controllers/AccountsController.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
As discussed, this will paginate on Operations so it's always better than querying all Operations and all ERC20Operations ...
Best solution is to not use this call, query ERC20Operations by batching them, then map from Gate's side (because also Gate is supposed already to have Operations)
This will also avoid doing the complete query
=> Batch erc20 ops

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
Because ambiguous column name (`erc20_operations` and `operation`)
TODO: this needs a fix from libcore to avoid ambiguous call on `ORDER BY date`
=> Remove order on ERC20 query operation 

src/it/scala/co/ledger/wallet/daemon/api/TransactionsApiTest.scala, src/main/scala/co/ledger/wallet/daemon/controllers/TransactionsController.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala
This enable partial btc like transac creation in order to avoid unnecessary costly operation on UTXOs info retrieval
=> [Back-374] - partial transaction creation (calculate fees more quickly)

src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
* Retrieve all token addresses and batch on erc20
* Replace old getERC20Balance when it is possible
* Single token get balance is using also batched method
/!\ **This PR is relying on this one https://github.com/LedgerHQ/djinni/pull/41 which fix a JNI issue. Please consider status it before merging this one.**
=> [Back-379] Batch erc20 balances to core lib

src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClient.scala, src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpUrlConnection.scala
Ensure connection is closed enven if error are thrown at read body time or on core side
Refactor a bit ScalaHttpClient by isolate action inside methods
=> [BACK-403] refactor and safe closing policy for lib-core http client

src/it/scala/co/ledger/wallet/daemon/api/AccountsApiTest.scala, src/main/scala/co/ledger/wallet/daemon/controllers/AccountsController.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
Expose the ability to list utxo from BTC accounts
- Test are not complete as there is no available account ready for this scenario on tests (ie with utxo on it) need to integrate an account with utxos
- The only test done for now is check that service is returning 200 http code
- Number of confirmation are not available yet so we are returning 0 for now
Usage Exemple :
`/pools/:pool_name:/wallets/:wallet_name:/accounts/:idx:/utxo?offset=3&batch=5`
Where _offset_ is the index of utxo from which we want to list and _batch_ the maximum size of returned list. If non of them are provided default values are _offset=0_ & _batch=Integer.MAX_VALUE_
=> Back-501 : list utxos for BTC Accounts

src/it/resources/application.conf, src/it/scala/co/ledger/wallet/daemon/api/AccountsApiTest.scala, src/it/scala/co/ledger/wallet/daemon/api/XRPAccountsApiTest.scala, src/it/scala/co/ledger/wallet/daemon/clients/ApiClientTest.scala, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/controllers/TransactionsController.scala, src/main/scala/co/ledger/wallet/daemon/controllers/requests/CommonMethodValidations.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/TransactionsService.scala
Harmonization of Create transaction payloads
- All BTC/ETH/XRP create transaction payload has `fees_level` field which is an enum value {`SLOW`, `NORMAL`, `FAST`}. 
- User can **override** fees by setting `fees` field on payload.
- Validation methods are ensuring that at least one of them is setup and will reject any request without at least fees or fees_level filled.
______________________
The fees level defines the amount of fees used according the current network load : 
**BTC** : 
- _SLOW_ : returned by explorer, amount to be included in the nexts 6 blocks 
- _NORMAL_ : returned by explorer, amount to be included in the nexts 3 blocks 
- _FAST_ : returned by explorer, amount to be included in the nexts 2 blocks 
**ETH** : Network `Gas Price * ETH_XXX_FEES_FACTOR` (configurable)
- …
=> [Back-582] fees harmonization across coins 

src/main/resources/application.conf.sample
This PR adds the "GET fee" endpoint for qtum on wallet daemon in order to be able to create
Qtum transactions on ledger vault
=> BACK-708 : Add Qtum support on Ledger Wallet Daemon

.circleci/config.yml
our dockerhub account is full, we will migrate to githubpkg
This patch publish the image on both registry
In order to work, an admin should go to
https://github.com/LedgerHQ/ledger-wallet-daemon/settings/access
and add "ldg-github-ci" with role "Write"
=> publish docker image to githubpkg

src/it/resources/application.conf, src/main/scala/co/ledger/wallet/daemon/clients/ApiClient.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
Libcore is returning -1 for unconfirmed utxos. Today we are not handling properly this property and this lead to wrong confirmation number computation on WD
So we keep as it when block-height is negative, otherwise we compute confirmations with `latestWalletKnownBlockHeight - utxoBlockHeight`
=> Back 866 wrong height on unconfirmed utxos

src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/configurations/DaemonConfiguration.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala
Expose ETH_SMART_CONTRACT_GAS_LIMIT_FACTOR for custom gaslimit factor policy on smart contracts
By default this factor is equal to 2 as requested.
see : https://ledgerhq.atlassian.net/browse/BACK-831
And https://ledgerhq.atlassian.net/browse/LV-2481
For more details.
This is globally a workaround for rounded gaslimit on the estimate_gas chain (explorer are suspected)
=> BACK-831 : Configurable factor for smart contract gaslimit

src/main/scala/co/ledger/wallet/daemon/models/Account.scala
There are two situations when a raw transaction is built by the wallet daemon:
1. Computing fees.
2. Building the actual transaction to sign.
Recently, #272 (JIRA: BACK-831) was introduced to double the gas limit estimates provided by the explorers. However, this doubling should only be done when the Gate has not specified the precise gas limit to be used for transaction creation, otherwise, the gas limit will be quadrupled instead of doubled.
=> BACK-831: Fix regression due to doubling of gas limit

src/it/resources/application.conf, src/it/scala/co/ledger/wallet/daemon/services/AccountSynchronizerManagerTest.scala, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/modules/PublisherModule.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountOperationsPublisher.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountSyncModule.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala, src/main/scala/co/ledger/wallet/daemon/services/Publisher.scala
The AccountSynchronizer does not block threads anymore. 
It delegates operations publishing to another actor. 
Both AccountSynchronizer and AccountOperationsPublisher share the same wd-blocking dispatcher for libcore jobs.
=> BACK-1079 AccountSynchronizer becomes an Actor

src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountOperationsPublisher.scala
Current implementation register a receiver on one event bus and unregister it on another.
This PR retains the synchronization event bus until the synchronization is over. Otherwise the daemon never gets notified of new synchronization events.
This PR also publishes account state for ETH accounts.
This PR also publishes unconfirmed (mempool) transaction when the "repush" endpoint is called.
=> Fix: retain synchronization event bus

src/it/resources/application.conf, src/main/resources/application.conf.sample, src/main/scala/co/ledger/wallet/daemon/clients/ClientFactory.scala, src/main/scala/co/ledger/wallet/daemon/clients/HttpCoreClientPool.scala
Add a auto-retry mechanism on HTTP client to retry all calls which returns an error 5XX. The numbers of retry can be changed by using the env variable CORE_HTTP_RETRIES
=> Add retry mechanism on http client given to ledger core

src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClientPool.scala
This release:
- Allow Netty to load larger HTTP response payloads which is needed to handle some big calls to V3 explorers.
=> Prepare 2.8.1-h2 release

src/main/resources/logback.xml, src/main/scala/co/ledger/wallet/daemon/clients/HttpCoreClientPool.scala, src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClientPool.scala, src/main/scala/co/ledger/wallet/daemon/libledger_core/logger/NoOpLogPrinter.scala, src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
* Global wallet daemon logger level is info for production
* Do not duplicate http client log when receive explorer response
* Enhance request and response logging from 200 to 400 char truncated
* Libcore is now logging at **error** level for production
=> BACK-1320 : Log verbosity reduction

src/it/resources/logback-test.xml, src/main/resources/application.conf.sample, src/main/resources/logback.xml, src/main/scala/co/ledger/wallet/daemon/clients/HttpCoreClientPool.scala, src/main/scala/co/ledger/wallet/daemon/clients/ScalaHttpClientPool.scala, src/main/scala/co/ledger/wallet/daemon/utils/NativeLibLoader.java
Inspired by [this commit](https://github.com/LedgerHQ/ledger-wallet-daemon/commit/98b0d0a187a9151e40cff867093e3d6aaf390746).
It takes an even more radical stand (info changed to warn), proposition is that we will come back to it if we need some special debug. But at least, we might be able to convince intra to send all the logs to the datadogs.
=> [BACK-1486] Make the logs great again

src/main/scala/co/ledger/wallet/daemon/services/AccountOperationsPublisher.scala, src/main/scala/co/ledger/wallet/daemon/services/Publisher.scala, src/main/scala/co/ledger/wallet/daemon/services/RabbitMQPublisher.scala
Adds:
- token family
- token name
- change publishERC20Account base method to take whole Pool instead of just poolName
=> Fix ERC20 publish message format

src/main/scala/co/ledger/wallet/daemon/database/core/WalletPoolDao.scala, src/main/scala/co/ledger/wallet/daemon/database/core/operations/ERC20Dao.scala, src/main/scala/co/ledger/wallet/daemon/database/core/operations/EthereumDao.scala, src/main/scala/co/ledger/wallet/daemon/models/Account.scala, src/main/scala/co/ledger/wallet/daemon/services/AccountsService.scala
This PR solves BACK-1565 wheer every single operations were pushed instead of all operations from the given block height.
It does so through the usage of WalletPoolDao, to continue the replacement of going through Libcore's dedicated system.
=> [BACK-1565] Add implementation of fetching ERC20 operations from last block height
